name: flutter_animation_sample
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cat.jpg
    - assets/images/cat2.webp
    - assets/images/cat3.webp
    - assets/images/flutter.png
    - assets/images/dash.png
    - assets/images/dash2.png
    - assets/images/dash3.png
